### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by JakariaJishan** [adelphinsucasa/Capstone-Project-with-Kanban-board#23]
You did a good job. Your project is amazing. One thing I want to suggest.
- When I add a new comment, it is not appearing immediately in the comments counter and is not displaying comments. but when I close the popup and again view the comments popup then it shows the updated comments. I think it would be better if you implement functionality when you add a new comment it will immediately display the updated comment.

**Comment by adelphinsucasa** [comment]
Thank you very much, it is done
